export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const CHANGE_LOCAL_LANGUAGE = 'CHANGE_LOCAL_LANGUAGE'
export const CHANGE_LANGUAGE_SUCCESS = 'CHANGE_LANGUAGE_SUCCESS'
export const CHANGE_LANGUAGE_LOCAL_SUCCESS = 'CHANGE_LANGUAGE_LOCAL_SUCCESS'
export const CHANGE_LANGUAGE_FAILED = 'CHANGE_LANGUAGE_FAILED'

// Auth
export const LOGIN_USER = 'LOGIN_USER'

export const NAV_INDEX ={
    STAFF:1,
    TEACHER:2,
    STUDENT:3,
}